### PR TITLE
feat: add `dependabot_alert` event

### PR DESCRIPTION
**Pull request by JamieMagee**
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#dependabot_alert

TODO:
- [ ] Correctly type [`alert`][1] object

[1]: https://docs.github.com/en/rest/dependabot/alerts#get-a-dependabot-alert

### CODE REVIEW

**Review by nickfloyd — COMMENTED** [review]
This looks good so far.  Let me know when you're ready to take it out of draft.

**Comment by wolfy1339** [comment]
I got the schema done on my side: https://github.com/octokit/webhooks/pull/718/commits/c34ecb6fe5301f4322e4f4fca4ec3c8b79599fb2

**Comment by JamieMagee** [comment]
Ready for review now.

There's a lot of duplication between the `dependabot_alert` and the `security_advisory` events, and refactoring to shared common models would reduce this, but that would be a breaking change so I am sticking with this approach for now.

**Review by nickfloyd — APPROVED** [review]
This looks great. No action need, just a side note for future reference about the `state` enum that we need to be aware of in octokit.net 
- create can be `dismissed`, `open` only
- list items can be `dismissed`, `fixed`, `open`
- update can be `dismissed`, `open` only

**Pull request merged**
