### PR TITLE
feat: add additional configuration option

### LINKED ISSUE #567: [FEAT]: Allow to configure secret using IConfiguration instance
### Describe the need

Currently, it's only possible to configure GitHub webhooks secret by passing the string to `ConfigureGitHubWebhooks` (at least if you don't manually want to configure `GitHubWebhooksOptions`). I suggest adding a configuration extension method that accepts a `Func<IConfiguration, string>` to retrieve the secret from configuration sources, allowing for a more dynamic configuration.

```c#
new HostBuilder()
    .ConfigureServices(collection =>
    {
        collection.AddSingleton<WebhookEventProcessor, MyWebhookEventProcessor>();
    })
    .ConfigureGitHubWebhooks((configuration) => configuration.GetValue<string>("GitHubWebhookSecret"))
    .ConfigureFunctionsWorkerDefaults()
    .Build()
    .Run();
```

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ganhammar**
Resolves #567 

----

### Before the change?

* Currently, it's only possible to configure `GitHubWebhooksOptions` using a static value, at least through the extension method

### After the change?

* With this PR, another configuration option has been added that allows to configure `GitHubWebhooksOptions` through an `IConfiguration` instance

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Review by nickfloyd — DISMISSED** [review]
Hety @ganhammar Thanks for the changes here! ❤️ It would be awesome to get some tests in here as well if / when you have time.

**Comment by ganhammar** [comment]
Hey @nickfloyd!

I have added a new test project for `Octokit.Webhooks.AzureFunctions` and tests covering the added extension method and the one that already existed. Let me know if any additional changes is needed 🙂

**Comment by ganhammar** [comment]
Any interest of this PR or should I close it? 😊

**Comment by nickfloyd** [comment]
> Any interest of this PR or should I close it? 😊

Definitely interest.  Thank you for the efforts.  We're just a bit behind on cycling through all of the reviews across Octokit.  We'll need to retrigger ci to get things verified, once that's done we should be able to ✅ and merge your changes in.

**Review by nickfloyd — APPROVED** [review]

**Pull request merged**
