### PR TITLE
feat: new `PullRequestQueued` and `PullRequestDequeued` events

### PR DESCRIPTION
**Pull request by JamieMagee**
https://github.com/octokit/webhooks/commit/44b5c3c6aa56bb780b01f0af972942496c08a783

### CODE REVIEW

**Comment by nickfloyd** [comment]
Apologies for the delay on this one @JamieMagee I was out sick.  Thanks for getting this change in. I did go ahead and give it a look - so I'll retro ✅ just for consistency.

**Review by nickfloyd — COMMENTED** [review]
LGTM! Reviewed post-merge - ✅

**Comment by JamieMagee** [comment]
@nickfloyd sorry about that. I was too keen to get this in and cut a release. I'll be more patient, or reach out directly in future

**Comment by nickfloyd** [comment]
@JamieMagee no worries, I definitely do not want to be a roadblock to getting things out the door - fortunately, the amazing @kfcampbell just joined the team so hopefully, we'll be able to cover all of these types of things in a more timely way.

**Pull request merged**
