### PR TITLE
Split deserialisation from processing the webhook

### LINKED ISSUE #19: Make deserialization separate to processing the webhook
### Describe the feature

The `ProcessWebhookAsync(WebhookHeaders headers, string body)`  method deserializes the webhook payload and processes it. 

I would like to be able to override the method in a derived class but already have the model (`WebhookEvent`) available. 
What are your thoughts on changing the method to `public virtual Task ProcessWebhookAsync(WebhookHeaders headers, WebhookEvent webhookEvent)` and adding another method for the deserialisation - such as  `public virtual WebhookEvent DeserializeWebhookEvent(WebhookHeaders headers, string body)`

### PR DESCRIPTION
**Pull request by Marethyu1**
This would close #19 

- Allows consumers to override the `ProcessPullRequestWebhookAsync` method but not have to deserialize the models themselves. 
- Provides a new public method for deserialising the payload (`DeserializeWebhookEvent`)

Extra things to note:
- This would technically be a breaking change for anyone who has already overridden the `ProcessPullRequestWebhookAsync` method. 
- I am not sure how you would want to handle a failure to deserialise the model. At the moment it throws a very generic exception

### CODE REVIEW

**Comment by Marethyu1** [comment]
Move this back into a draft as I think there is a better way to do this

**Comment by Marethyu1** [comment]
@JamieMagee would love to see your thoughts on this 👍

**Comment by JamieMagee** [comment]
Sorry for leaving this so long to review. It looks good, my only question is about the warnings in the output

>Use 'switch' expression

I have `TreatWarningsAsErrors` and `EnforceCodeStyleInBuild` both enabled. Is it something you can do in your IDE?

**Comment by JamieMagee** [comment]
Thanks!

As for versioning and breaking changes, for packages that are <`1.0.0`, minor package version bumps are allowed to have breaking changes [^1]

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Though I should probably publish `1.0.0` soon.

[^1]: https://semver.org/#semantic-versioning-specification-semver

**Pull request merged**
