### PR TITLE
test: add tests for datetimeoffset converters

### PR DESCRIPTION
**Pull request by JamieMagee**
FYI: @tobysmith568

### CODE REVIEW

**Comment by tobysmith568** [comment]
Ah looks good @JamieMagee. Is it worth adding a test to each converter with a datetime in this format `2022-01-13T09:21:34.000+00:00` as it's also a format that the GitHub API sometimes returns? I also wonder if the unix timestamps in their tests should be ints rather than strings?

**Comment by JamieMagee** [comment]
I added tests for the other format. Unfortunately, `JsonSerializer.Deserialize` only takes `string` as a parameter so I can't pass an int directly, but I am passing the JSON equivalent of an int `@"123"` instead of `@"""123"""`

**Comment by tobysmith568** [comment]
Ah yeah that makes sense :)

**Comment by JamieMagee** [comment]
Super! I've merged this and cut a release with your changes 🎉

**Pull request merged**
