### PR TITLE
Add in_progress and queued to WorkflowJobStepConclusion enums

### LINKED ISSUE #169: [BUG]: WorkflowJobCompletedEvent cannot be Deserialized if the job was not successful
### What happened?

A workflow job ran and a step failed - a workflow_job.completed event is raised with the conclusion "failure" and in the `steps` collection the status of  one of the steps is `in_progress` this status is not included in the  [WorkflowJobStepConclusion](https://github.com/octokit/webhooks.net/blob/main/src/Octokit.Webhooks/Models/WorkflowJobEvent/WorkflowJobStepConclusion.cs) enum which causes the deserialization to fail and throw an error.

### Versions

Octokit.Webhooks.AspNetCore 1.3.5

### Relevant log output

```shell
System.ArgumentException: Requested value 'in_progress' was not found.
at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.<>c__DisplayClass7_0.<DeserializeEnumHelper>b__1(Object v) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/SimpleJsonSerializer.cs:line 137
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeEnumHelper(String value, Type type) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/SimpleJsonSerializer.cs:line 137
at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/SimpleJsonSerializer.cs:line 183
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mattdjones**
Resolves #169

----

### Before the change?
When a workflow_job.completed with a `failed` conclusion event is deserialized it fails because steps can have `in_progress` and `queued` status which are not included in the WorkflowJobStepConclusion enums

* 

### After the change?
The `in_progress` & `queued`  status steps can be deserialized for a workflowflow completed event with a failed conclusion and steps that are in_progress or queued.

* 

### Other information

* 

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
@mattdjones do you know if there's documentation somewhere specifying the possible states here? I can't seem to find it, unfortunately.

**Comment by wolfy1339** [comment]
I believe they may have been taken from [`@octokit/webhooks`](https://github.com/octokit/webhooks), and those were taken from  some examples submitted from real payloads.

**Comment by kfcampbell** [comment]
Hmm, I'm not seeing it [here](https://github.com/octokit/webhooks/blob/master/payload-schemas/api.github.com/common/workflow-job.schema.json#L50); am I looking in the wrong place?

**Comment by wolfy1339** [comment]
The PR addresses the `conclusion` for the `steps` in a `WorkflowJob` event.
Not to be confused with the conclusion for the `WorflowJob` itself

https://github.com/octokit/webhooks/blob/master/payload-schemas/api.github.com/common/workflow-step-completed.schema.json

https://github.com/octokit/webhooks/blob/master/payload-schemas/api.github.com/common/workflow-step-in_progress.schema.json

**Comment by mattdjones** [comment]
hey @kfcampbell sorry I can't the staes detailed in the [docs](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_job)

**Comment by kfcampbell** [comment]
Understood, thank you both!

**Comment by mattdjones** [comment]
hey @kfcampbell  & @wolfy1339  do I need to add anything else to get this merged?

**Comment by wolfy1339** [comment]
I'm not a maintainer for the .NET packages, so I cannot help here.

Although, it looks fine to me.

**Review by kfcampbell — APPROVED** [review]
Nope, I'll get this merged. If you have an example payload that could help illustrate the need, that would be nice to comment on this PR for historical reference.

**Comment by mattdjones** [comment]
thanks @kfcampbell  no problem, do you mean add it to this PR description?

**Pull request merged**
