### PR TITLE
Support hot-swapping of webhok secrets

### LINKED ISSUE #24: Refactor X-Hub-Signature validation
### Describe the feature

https://github.com/octokit/webhooks.net/blob/95e10f99238339f5ae712e73b5f4279debef7646/src/Octokit.Webhooks.AspNetCore/GitHubWebhookExtensions.cs#L66 requires a `HttpContext` object only for its `header` and for generating a response in the case of failure.  Unfortunately. `HttpContext`s are sometimes hard to come by; for example, Azure Functions, at least as of runner version 4, for example, provide only `HttpRequest`s and not the full `HttpContext`.

Therefore, it would be quite nice and DRY if this method could be split into a worker and wrapper, with the worker taking the already-extracted signature header and returning a `HttpStatusCode` and `String` for the body, and the wrapper adapting for the ASP.Net `HttpContext` object.

### LINKED ISSUE #261: [FEAT]: Support hot-swapping of webhook secrets
### Describe the need

In my GitHub app, I have a couple different situations in which I'd like to support changing the webhook secret without restarting my service:

### Initial configuration
Instances of my app are deployed via the GitHub App flow, where I create a new GitHub App from a manifest. When I first deploy a new instance of my service, it hasn't been registered as a GitHub app yet, so I don't yet know its webhook secret. Therefore, it should not accept any webhooks yet. Once the app registration is complete, though, I obtain the webhook secret for the new app, and I'd like to start accepting webhooks validated against that secret.

### Secret rotation
I'd like to rotate my webhook secret periodically, or at least allow for a situation where my secret has been compromised and I need to manually change it. With the current code, I'd have to at least restart every service instance in my cluster just to update the secret. In addition, there could be webhooks already in flight for the old key, and I'd like to have a short period where I accept webhook requests that are signed with either the old or the new secret.

I'll open an initial PR shortly. As a bonus, I'll take care of existing issue #24, since I have to make changes to the validation code anyway.

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dbartol**
Resolves #261
Resolves #24

----

(In draft until I finish implementing tests)

### Before the change?

* In both ASP.NET Core and Azure Functions, the webhook secret for the webhook processor must be specified when the processor is registered, and cannot be changed afterward. In addition, there can be only one secret specified.

### After the change?

* A client now has the option of specifying a callback delegate to retrieve the list of secrets to validate against. This callback will be invoked for each request, so the results can change dynamically to allow rotation of the secret. In addition, the callback can return multiple secrets, with the request's signature required to match at least one of those secrets.

### Other information

Since the request validation code that I was modifying was duplicated between the ASP.NET Core and Azure Functions packages, I took the opportunity to refactor the validation code to allow sharing (see #24). I chose to add the new `ValidateWebhookRequestAsync()` method to the existing `WebhookEventProcessor` class. It could go in a separate class, but I figured that most clients that process webhooks will also need to validate them. I'm tempted to also add a new `ValidateAndProcessWebhookAsync()` method that does both the validation and the processing, since they take essentially the same parameters and will almost always be used together. I didn't go that far in this PR, though.

The parameter types for the new `ValidateWebhookRequestAsync()` method include the request headers (as the same type used for `ProcessWebhookAsync()`), the body `Stream`, and the list of secrets to use. Allowing multiple secrets allows secret rotation to happen more smoothly, because the consumer can continue to process webhooks signed with the old secret for a while until everything starts using the new secret.

Passing the body as a `Stream` seems to be the least common denominator between the ASP.NET Core and Azure Functions packages, and is likely useful outside of those two scenarios. I considered just passing the body as a `string`, but that would make it more difficult to implement a defensive check against a maliciously large payload. That check was suggested in #24, but I have not implemented it here.

Validation errors are reported by throwing a `WebhookValidationException`. This class contains a `WebHookValidationError` enum that allows clients to determine exactly what went wrong. The two existing clients use this to determine what log message to emit, and what response text, if any, to return.

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [ ] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by JamieMagee** [comment]
@dbartol before you go too deep on this, would the [`IOptionsSnapshot`][1] pattern work?

[1]: https://learn.microsoft.com/en-us/dotnet/core/extensions/options#use-ioptionssnapshot-to-read-updated-data

**Comment by dbartol** [comment]
@JamieMagee Thanks for the pointer. This might fit better with `IOptionsMonitor` from that same link, since I'd expect the webhook processor to be a singleton. I'll give that a shot.

In any case, most of the work here was the refactoring, which should be helpful even without any hot-swapping support. If you'd prefer, I can take out the hot-swapping part of this PR and just leave the refactoring and multi-secret support while I try out `IOptionsMonitor`.

**Comment by JamieMagee** [comment]
Yeah, if it's not too much trouble, could you separate out the refactoring from the implementation with `IOptionsMonitor`?

**Review by justinmchase — APPROVED** [review]
I was thinking you would want an `IGithubWebhookSecretResolver` service instead of just a plain callback function but this is probably ok.

**Comment by JamieMagee** [comment]
@justinmchase I don't have permissions in this repository at the moment, but this PR isn't ready to be merged.

I'll followup with @dbartol, but I suspect he isn't going to pick this back up. In which case, I'll take on the refactor once I get my permissions back.

**Comment by justinmchase** [comment]
Sure, but in general I filed an issue a couple of days ago that this would fix, so one way or another the general idea of this PR looks pretty good.

**Comment by JamieMagee** [comment]
Closing this in favour of #550

**Pull request closed without merging**
