### PR TITLE
Ilmax/extensions

### PR DESCRIPTION
**Pull request by ilmax**
This PR simplifies implementing custom payloads that're not yet supported in the current package, e.g. `deployment_review`, will help with #53 and #297. The pain point was that the mechanism used to figure out which type to use to deserialize the payload was internal and was only scanning the `Octokit.Webhooks` assembly for types.

With these minimal changes we more easily implement the missing payloads

### CODE REVIEW

**Comment by JamieMagee** [comment]
I'm not sure this is a necessary extensions. Yes, the `deployment_review` is missing right now. But we're working to try and publish the schema.

Aside from that, why would you not contribute back the object implementation to this repository?

**Comment by ilmax** [comment]
@JamieMagee thank you for your answer. I'm not contributing back the object implementation because I don't know the shape of the object so I can only contribute an "educated guess" implementation, this was a way to unblock people so that they can implement the `deployment_review` object in their code without having to also implement the deserialization mechanism that's already in place.

> But we're working to try and publish the schema.

Please note that there's an issue #53 open for almost 1 year and a half on exposing such object

**Comment by ilmax** [comment]
@JamieMagee any response on my last comment?

**Comment by JamieMagee** [comment]
New event documentation is available:
- [`deployment_review`][1]
- [`merge_queue_entry`][2]
- [`repository_ruleset`][3]

[1]: https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#deployment_review
[2]: https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#merge_queue_entry 
[3]: https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#repository_ruleset

**Pull request closed without merging**
